version: "3.3"
services:
  inventory-api:
    build: .
    image: inventory/api
    command: npm run dev
    volumes:
      - .:/app
      - build:/app/build
      - node_modules:/app/node_modules/
    env_file:
      - ./env.development
    links:
      - inventory-db
    ports:
      - 3000:3000
      - 9229:9229
  inventory-db:
    image: "postgres:11.5"
    container_name: "inventory-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=inventory
    ports:
      - "5432:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
volumes:
  inventory_data:
  build:
  node_modules:
